# Generated by Django 2.1.5 on 2019-02-17 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='max_backups',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
