# Generated by Django 2.1.5 on 2019-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190217_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
