# Generated by Django 2.1.5 on 2019-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
