# Generated by Django 2.1.5 on 2019-05-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20190217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backup_size',
            field=models.CharField(default='0 bytes', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='backup',
            name='contains_settings',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='backup',
            name='events_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='backup',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='backup',
            name='digest',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
