# Generated by Django 2.1.5 on 2019-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_auto_20190511_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='events_amount',
            new_name='events_count',
        ),
    ]
